export const API_BASE_URL = import.meta.env.VITE_API_URL || 'http://localhost:5000/api';

export const LUXURY_THEME = {
  primaryBrown: '#8B7355',
  warmBrown: '#A0826D',
  warmBeige: '#F5E6D3',
  cream: '#FFFAF0',
  dark: '#2D2D2D',
  muted: '#666666',
  offwhite: '#FAFAF8',
  gold: '#C5A059',
};

export const FEATURED_DESTINATIONS = [
  {
    id: 'dest-hernur',
    name: 'Hernur',
    region: 'Riviera Reserve',
    tagline: 'Golden limestone cliffs & secluded yacht bays',
    rating: 4.98,
    reviewsCount: 384,
    bestTimeToVisit: 'May – October',
    flightTimeFromNYC: '7h 15m (Direct VIP)',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
    description: 'A sanctuary of dramatic promontories, private coves, and centuries-old olive terraces.',
    startingPrice: 1250,
  },
  {
    id: 'dest-panling',
    name: 'Panling',
    region: 'Emerald Atoll',
    tagline: 'Overwater pavilions & private starlit dining',
    rating: 4.96,
    reviewsCount: 412,
    bestTimeToVisit: 'Year-Round Sanctuary',
    flightTimeFromNYC: '12h 40m',
    image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=800&q=80',
    description: 'Crystal-clear sapphire waters bordered by soft coral sands and five-star floating villas.',
    startingPrice: 1890,
  },
  {
    id: 'dest-famling',
    name: 'Famling',
    region: 'Heritage Vineyards',
    tagline: 'Private château estates & Michelin-starred cellars',
    rating: 4.94,
    reviewsCount: 298,
    bestTimeToVisit: 'September – November',
    flightTimeFromNYC: '6h 45m',
    image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
    description: 'Rolling hills draped in Pinot Noir vines, private equestrian tours, and historic château residences.',
    startingPrice: 980,
  },
  {
    id: 'dest-vouke',
    name: 'Vouke',
    region: 'Alpine Glaciers',
    tagline: 'Helicopter ski drops & wood-fired thermal spas',
    rating: 4.97,
    reviewsCount: 260,
    bestTimeToVisit: 'December – April',
    flightTimeFromNYC: '8h 20m',
    image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80',
    description: 'Snow-capped solitude, private glass chalets, and Michelin dining beside roaring open hearths.',
    startingPrice: 1450,
  },
  {
    id: 'dest-cedling',
    name: 'Cedling',
    region: 'Cedar Forest Sanctuary',
    tagline: 'Holistic wellness & Japanese onsen philosophy',
    rating: 4.95,
    reviewsCount: 215,
    bestTimeToVisit: 'April – June',
    flightTimeFromNYC: '11h 10m',
    image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=800&q=80',
    description: 'Centuries-old cedar forests, private hot springs, and serene architecture for mindful restoration.',
    startingPrice: 1100,
  },
  {
    id: 'dest-paride',
    name: 'Paride',
    region: 'Metropolitan Art District',
    tagline: 'Haute couture private salons & curated galleries',
    rating: 4.99,
    reviewsCount: 540,
    bestTimeToVisit: 'Spring & Autumn',
    flightTimeFromNYC: '7h 00m',
    image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=800&q=80',
    description: 'The epicenter of art, private after-hours museum viewings, and bespoke fashion houses.',
    startingPrice: 1650,
  },
];
